name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4

      - run: pnpm install --frozen-lockfile

      - name: Create GitHub Release
        run: pnpm run gh:release
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: pnpm run build

      - name: Package VSIX
        run: pnpm exec vsce package --no-dependencies

      - name: Publish to VS Code Marketplace
        run: pnpm exec vsce publish --no-dependencies -p ${{secrets.VSCE_TOKEN}}
        env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}

      - name: Publish to Open VSX
        if: success() || failure()
        run: pnpm exec ovsx publish *.vsix -p ${{secrets.OVSX_TOKEN}}
        env:
          OVSX_TOKEN: ${{secrets.OVSX_TOKEN}}

      - name: Upload VSIX to GitHub Release
        run: gh release upload ${{github.ref_name}} *.vsix --clobber
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
